openapi: 3.0.3


info:
  title: 'Test'
  description: This is a sample description
  termsOfService: https://example.com
  version: '1.0'
  license:
    name: Fictional license
    url: https://example.com
  contact:
    email: fakeemail@provider.com
    name: saraflower
    url: https://example.com


servers:
- url: https://qa.example.com
  description: QA Example server
- url: https://prod.example.com
  description: Prod Example server


paths:
  /v1/customers:
    get:
      summary: List Customers
      description: Get all customers paged
      operationId: V1ListCustomers
      tags:
        - Customers
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageNumber'
      responses:
        '200':
          description: List of Customers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerPagedList"
    post:
      summary: New Customer
      description: Create a new customer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer Created
          headers:
            location:
              description: Location of the created customer
              schema:
                type: string
                format: uri
                example: http://example.com/v1/customers/{assignedIdValue}
        

  /v1/customers/{customerId}:
    get:
      summary: Single customer
      description: Get customer by id
      tags:
        - Customers
      operationId: V1CustomerById
      parameters:
        - $ref: '#/components/parameters/customerId'
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    put:
      summary: Update Customer
      description: Update customer by id
      tags:
        - Customers
      parameters:
        - $ref: '#/components/parameters/customerId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '204':
          description: Customer updated

  /v1/drinks:
    get:
      summary: List drinks
      description: Get all drinks paged
      tags:
        - Drinks
      operationId: V1ListDrinks
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageNumber'
      responses:
        '200':
          description: List of Drinks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DrinkPagedList"
        '404':
          description: Not found
    post:
      summary: New Drink
      description: Create a new Drink
      tags:
        - Drinks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: Drink
      responses:
        '201':
          description: Drink Created
          headers:
            location:
              description: Location of the created drink
              schema:
                type: string
                format: uri
                example: http://example.com/v1/drinks/{assignedIdValue}

  /v1/drinks/{drinkId}:
    get:
      summary: Single Drink
      description: Get drink by id
      tags:
        - Drinks
      operationId: V1DrinkById
      parameters:
        - $ref: '#/components/parameters/drinkId'
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema:
                $ref: Drink
    put:
      summary: Update Drink
      description: Update drink by id
      tags:
        - Drinks
      parameters:
        - $ref: '#/components/parameters/drinkId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: Drink
      responses:
        '204':
          description: Customer updated  

components:
  parameters:
    pageSize:
      name: pageSize
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 25
    pageNumber:
      name: pageNumber
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 1
    customerId:
      name: customerId
      in: path
      description: Customer Id
      required: true
      schema:
        type: string
        format: uuid
    drinkId:
      name: drinkId
      in: path
      description: Drink Id
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    Address:
      type: object
      description: Address Object
      properties:
        line1:
          type: string
          example: Street 123-5
        city:
          type: string
          example: Valencia
        zipCode:
          type: string
          example: 55555
        province:
          type: string
          enum: [VAL, BCN, MAD]
        community:
          type: string
          enum:
            - Comunitat Valenciana
            - Barcelona
            - Madrid

    User:
      type: object
      description: base user
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        username:
          type: string

    Customer:
      type: object
      description: Customer Object
      allOf:
        - $ref: '#/components/schemas/User'
      properties:
        firstName:
          type: string
          minLength: 2
          maxLength: 100
          example: Sara
        lastName:
          type: string
          minLength: 2
          maxLength: 100
          example: Flower
        address:
          $ref: "#/components/schemas/Address"

    CustomerList:
      type: array
      items:
        $ref: "#/components/schemas/Customer"

    CustomerPagedList:
      type: object
      allOf:
        - $ref: ./PagedResponse/PagedResponse.yaml
      properties:
        content:
          $ref: '#/components/schemas/CustomerList'

    DrinkPagedList:
      type: object
      allOf:
        - $ref: ./PagedResponse/PagedResponse.yaml
      properties:
        content:
          $ref: DrinkList.yaml
