openapi: 3.0.3


info:
  title: 'Test'
  description: This is a sample description
  termsOfService: https://example.com
  version: '1.0'
  license:
    name: Fictional license
    url: https://example.com
  contact:
    email: fakeemail@provider.com
    name: saraflower
    url: https://example.com


servers:
- url: https://qa.example.com
  description: QA Example server
- url: https://prod.example.com
  description: Prod Example server


paths:
  /v1/customers:
    get:
      responses:
        '200':
          description: List of Customers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: Customer Object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: Sara
                    lastName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: Flower
                    address:
                      type: object
                      description: Address Object
                      properties:
                        line1:
                          type: string
                          example: Street 123-5
                        city:
                          type: string
                          example: Valencia
                        zipCode:
                          type: string
                          example: 55555
                        province:
                          type: string
                          enum: [VAL, BCN, MAD]
                        community:
                          type: string
                          enum:
                            - Comunitat Valenciana
                            - Barcelona
                            - Madrid

  /v1/drinks:
    get:
      responses:
        '200':
          description: List of Drinks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: Drink Object
                  properties:
                    name:
                      type: string
                      example: Best drink
                    style:
                      type: string
                      enum:
                        - HOT
                        - COLD
                    price:
                      type: number
                      format: float
                      example: 5.50
                    stock:
                      type: integer
                      format: int32
                      example: 123
        '404':
          description: Not found