openapi: 3.0.3


info:
  title: 'Test'
  description: This is a sample description
  termsOfService: https://example.com
  version: '1.0'
  license:
    name: Fictional license
    url: https://example.com
  contact:
    email: fakeemail@provider.com
    name: saraflower
    url: https://example.com


servers:
- url: https://qa.example.com
  description: QA Example server
- url: https://prod.example.com
  description: Prod Example server


paths:
  /v1/customers:
    get:
      responses:
        '200':
          description: List of Customers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerList"


  /v1/drinks:
    get:
      responses:
        '200':
          description: List of Drinks
          content:
            application/json:
              schema:
                $ref: DrinkList.yaml
        '404':
          description: Not found


components:
  schemas:
    Address:
      type: object
      description: Address Object
      properties:
        line1:
          type: string
          example: Street 123-5
        city:
          type: string
          example: Valencia
        zipCode:
          type: string
          example: 55555
        province:
          type: string
          enum: [VAL, BCN, MAD]
        community:
          type: string
          enum:
            - Comunitat Valenciana
            - Barcelona
            - Madrid

    User:
      type: object
      description: base user
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string

    Customer:
      type: object
      description: Customer Object
      allOf:
        - $ref: '#/components/schemas/User'
      properties:
        firstName:
          type: string
          minLength: 2
          maxLength: 100
          example: Sara
        lastName:
          type: string
          minLength: 2
          maxLength: 100
          example: Flower
        address:
          $ref: "#/components/schemas/Address"

    CustomerList:
      type: array
      items:
        $ref: "#/components/schemas/Customer"

    PagedResponse:
      type: object
      properties:
        pageable:
          $ref: '#/components/schemas/PagedResponse_pageable'
        totalPages:
          type: integer
          format: int32
        last:
          type: boolean
        totalElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        numberOfElements:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/PagedResponse_pageable_sort'
        first:
          type: boolean
    PagedResponse_pageable_sort:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
    PagedResponse_pageable:
      type: object
      properties:
        sort:
          $ref: '#/components/schemas/PagedResponse_pageable_sort'
        offset:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean